# Generated by Django 4.0.3 on 2022-12-05 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mass', models.FloatField()),
                ('gravity_constant', models.FloatField()),
                ('volume', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PlanetaryBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mass', models.FloatField()),
                ('gravity_constant', models.FloatField()),
                ('volume', models.FloatField()),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planetary_play.planet')),
            ],
        ),
    ]
